// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmNs6edTWhyPKLeniXXbzLKi16if5ZGBI',
    appId: '1:956961195591:web:ff609a5114cf8863375362',
    messagingSenderId: '956961195591',
    projectId: 'nomadthread-e9e06',
    authDomain: 'nomadthread-e9e06.firebaseapp.com',
    storageBucket: 'nomadthread-e9e06.appspot.com',
    measurementId: 'G-STMML603J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFD_8eFks11eod5Aa0iBNVug_5eV3ByN8',
    appId: '1:956961195591:android:fb13e967e471f919375362',
    messagingSenderId: '956961195591',
    projectId: 'nomadthread-e9e06',
    storageBucket: 'nomadthread-e9e06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqESqoF7W7oY4jmF371x7nda2gquAhMCE',
    appId: '1:956961195591:ios:550c985c101123f3375362',
    messagingSenderId: '956961195591',
    projectId: 'nomadthread-e9e06',
    storageBucket: 'nomadthread-e9e06.appspot.com',
    iosClientId: '956961195591-lc5f7pmrgjjl2a4maa0hlevnfbagubgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.assign11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqESqoF7W7oY4jmF371x7nda2gquAhMCE',
    appId: '1:956961195591:ios:d42e005126875473375362',
    messagingSenderId: '956961195591',
    projectId: 'nomadthread-e9e06',
    storageBucket: 'nomadthread-e9e06.appspot.com',
    iosClientId: '956961195591-2jsfoe43s5j5njdvm3uo23pikdkvroip.apps.googleusercontent.com',
    iosBundleId: 'com.example.assign11.RunnerTests',
  );
}
